### ISSUE TITLE
How to make ImageSets file？I can't find any tutorial about it 

### ISSUE THREAD

**Issue by Chengnotwang** [EdwardDo69/D3T#1]
![image](https://github.com/EdwardDo69/D3T/assets/109078083/12fd7101-2263-4bd0-8f04-d24a9ecc8c89)

**Comment by Manjuphoenix** [comment]
And how is the folder D3T_flir created before training?
As mentioned here: https://github.com/EdwardDo69/D3T?tab=readme-ov-file#training

**Comment by EdwardDo69** [comment]
Here are the corrected sentences:

Thank you for your attention. I apologize for my late answer due to some personal reasons.
1. I have re-uploaded the ImageSets file into "cvpods/data/FLIR_ICIP2020_aligned/ImageSets".
2. There were some typo errors. I have changed them in the "experiment/flir_rgb2thermal/" folder.
